### ISSUE TITLE
Can't reproduce the issue

### ISSUE THREAD

**Issue by borisyurkevich** [Qata/MonadicJSON#1]
Hello, I hope I am making an obvious mistake. But I have tried to reproduce Decimal conversion issue when decoding it from String and then returning it as a String as well. I have tried couple of "problematic" numbers included in the `JSONTests`, and I couldn't reproduce the problem using Xcode 10.2.1 and, possibly, Swift 5. I don't know how to check Swift version during runtime.

Example playground

```
import Foundation

struct DoubleItem : Codable {
    var name: String
    var price: Double
}

struct DecimalItem : Codable {
    var name: String
    var price: Decimal
}

struct StringItem : Codable {
    var name: String
    var price: String
}

let jsonString = """
{ "name": "Gum ball", "price": "1.1172404971672576"}
"""
let jsonData = jsonString.data(using: .utf8)!

let decoder = JSONDecoder()
do {
    let stringItem = try decoder.decode(StringItem.self, from: jsonData)
    print(stringItem)

    // Now get Decimal value
    let interface = Decimal(string: stringItem.price)
    print("interface: \(interface!)")
    if "\(interface!)" == "1.1172404971672576" {
        print("success")

        let encoder = JSONEncoder()
        do {
            let parcell = try encoder.encode(stringItem)
            print(String(data: parcell, encoding: .utf8)!)
        }
        catch {
            print("enc err")
            print(error)
        }
    }
}
catch {
    print(error)
}
```

**Output**

```
StringItem(name: "Gum ball", price: "1.1172404971672576")
interface: 1.1172404971672576
success
{"name":"Gum ball","price":"1.1172404971672576"}
```

**Comment by borisyurkevich** [comment]
Pay attention to the `interface`. There's no loss of precision. If I am right, this library is not necessary. JSONDecoder can handle this with no issues, and much faster.

**Comment by Qata** [comment]
Your test using a String and then a Decimal conversion is why there isn’t a loss of precision, you’re doing the same thing this library does but manually. 
I’ve written a lot of tests that prove this issue, please review them.
